// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:parking_management/app/di/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(AuthSessionAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(TariffAdapter());
    registerAdapter(TariffTypeAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserRoleAdapter());
    registerAdapter(VehicleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(AuthSessionAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(TariffAdapter());
    registerAdapter(TariffTypeAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserRoleAdapter());
    registerAdapter(VehicleAdapter());
  }
}
